source 'https://github.com/CocoaPods/Specs.git'

target 'SpriteKitAutoLayout', :exclusive => true do
  pod "SpriteKitAutoLayout", :path => "../"
end

target 'SpriteKitAutoLayoutOSX', :exclusive => true do
    platform :osx, '10.10'
    pod "SpriteKitAutoLayout", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "SpriteKitAutoLayout", :path => "../"

  
end
